# Generated by Django 2.2.4 on 2019-08-24 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_merge_20190821_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='unblockrequest',
            name='url',
            field=models.TextField(error_messages={'unique': 'This url is already under consideration'}, unique=True, validators=[django.core.validators.URLValidator(message='This is not a valid URL.')]),
        ),
    ]
